// Code generated by optiongen. DO NOT EDIT.
// optiongen: github.com/timestee/optiongen

package protokit

import (
	"sync/atomic"
	"unsafe"
)

// NamePattern should use NewNamePattern to initialize it
type NamePattern struct {
	// annotation@NamePatternServerHandler(comment="code server handler名称格式化")
	NamePatternServerHandler string `xconf:"name_pattern_server_handler" usage:"code server handler名称格式化"`
	// annotation@NamePatternRpcClient(comment="code rpc client名称格式化")
	NamePatternRpcClient string `xconf:"name_pattern_rpc_client" usage:"code rpc client名称格式化"`
	// annotation@NamePatternActorClient(comment="code actor client名称格式化")
	NamePatternActorClient string `xconf:"name_pattern_actor_client" usage:"code actor client名称格式化"`
	// annotation@NamePatternActorServerHandlerMethod(comment="actor server handler的方法名称格式化")
	NamePatternActorServerHandlerMethod string `xconf:"name_pattern_actor_server_handler_method" usage:"actor server handler的方法名称格式化"`
	// annotation@NamePatternSingleConfPackage(comment="生成golang conf时控制package名称，可用参数#file、#sheet")
	NamePatternSingleConfPackage string `xconf:"name_pattern_single_conf_package" usage:"生成golang conf时控制package名称，可用参数#file、#sheet"`
}

// NewNamePattern new NamePattern
func NewNamePattern(opts ...NamePatternOption) *NamePattern {
	cc := newDefaultNamePattern()
	for _, opt := range opts {
		opt(cc)
	}
	if watchDogNamePattern != nil {
		watchDogNamePattern(cc)
	}
	return cc
}

// ApplyOption apply mutiple new option and return the old ones
// sample:
// old := cc.ApplyOption(WithTimeout(time.Second))
// defer cc.ApplyOption(old...)
func (cc *NamePattern) ApplyOption(opts ...NamePatternOption) []NamePatternOption {
	var previous []NamePatternOption
	for _, opt := range opts {
		previous = append(previous, opt(cc))
	}
	return previous
}

// NamePatternOption option func
type NamePatternOption func(cc *NamePattern) NamePatternOption

// WithNamePatternServerHandler code server handler名称格式化
func WithNamePatternServerHandler(v string) NamePatternOption {
	return func(cc *NamePattern) NamePatternOption {
		previous := cc.NamePatternServerHandler
		cc.NamePatternServerHandler = v
		return WithNamePatternServerHandler(previous)
	}
}

// WithNamePatternRpcClient code rpc client名称格式化
func WithNamePatternRpcClient(v string) NamePatternOption {
	return func(cc *NamePattern) NamePatternOption {
		previous := cc.NamePatternRpcClient
		cc.NamePatternRpcClient = v
		return WithNamePatternRpcClient(previous)
	}
}

// WithNamePatternActorClient code actor client名称格式化
func WithNamePatternActorClient(v string) NamePatternOption {
	return func(cc *NamePattern) NamePatternOption {
		previous := cc.NamePatternActorClient
		cc.NamePatternActorClient = v
		return WithNamePatternActorClient(previous)
	}
}

// WithNamePatternActorServerHandlerMethod actor server handler的方法名称格式化
func WithNamePatternActorServerHandlerMethod(v string) NamePatternOption {
	return func(cc *NamePattern) NamePatternOption {
		previous := cc.NamePatternActorServerHandlerMethod
		cc.NamePatternActorServerHandlerMethod = v
		return WithNamePatternActorServerHandlerMethod(previous)
	}
}

// WithNamePatternSingleConfPackage 生成golang conf时控制package名称，可用参数#file、#sheet
func WithNamePatternSingleConfPackage(v string) NamePatternOption {
	return func(cc *NamePattern) NamePatternOption {
		previous := cc.NamePatternSingleConfPackage
		cc.NamePatternSingleConfPackage = v
		return WithNamePatternSingleConfPackage(previous)
	}
}

// InstallNamePatternWatchDog the installed func will called when NewNamePattern  called
func InstallNamePatternWatchDog(dog func(cc *NamePattern)) { watchDogNamePattern = dog }

// watchDogNamePattern global watch dog
var watchDogNamePattern func(cc *NamePattern)

// newDefaultNamePattern new default NamePattern
func newDefaultNamePattern() *NamePattern {
	cc := &NamePattern{}

	for _, opt := range [...]NamePatternOption{
		WithNamePatternServerHandler("ServerHandler%s"),
		WithNamePatternRpcClient("RpcClient%s"),
		WithNamePatternActorClient("ActorClient%s"),
		WithNamePatternActorServerHandlerMethod("%s"),
		WithNamePatternSingleConfPackage("%s"),
	} {
		opt(cc)
	}

	return cc
}

// AtomicSetFunc used for XConf
func (cc *NamePattern) AtomicSetFunc() func(interface{}) { return AtomicNamePatternSet }

// atomicNamePattern global *NamePattern holder
var atomicNamePattern unsafe.Pointer

// onAtomicNamePatternSet global call back when  AtomicNamePatternSet called by XConf.
// use NamePatternInterface.ApplyOption to modify the updated cc
// if passed in cc not valid, then return false, cc will not set to atomicNamePattern
var onAtomicNamePatternSet func(cc NamePatternInterface) bool

// InstallCallbackOnAtomicNamePatternSet install callback
func InstallCallbackOnAtomicNamePatternSet(callback func(cc NamePatternInterface) bool) {
	onAtomicNamePatternSet = callback
}

// AtomicNamePatternSet atomic setter for *NamePattern
func AtomicNamePatternSet(update interface{}) {
	cc := update.(*NamePattern)
	if onAtomicNamePatternSet != nil && !onAtomicNamePatternSet(cc) {
		return
	}
	atomic.StorePointer(&atomicNamePattern, (unsafe.Pointer)(cc))
}

// AtomicNamePattern return atomic *NamePatternVisitor
func AtomicNamePattern() NamePatternVisitor {
	current := (*NamePattern)(atomic.LoadPointer(&atomicNamePattern))
	if current == nil {
		defaultOne := newDefaultNamePattern()
		if watchDogNamePattern != nil {
			watchDogNamePattern(defaultOne)
		}
		atomic.CompareAndSwapPointer(&atomicNamePattern, nil, (unsafe.Pointer)(defaultOne))
		return (*NamePattern)(atomic.LoadPointer(&atomicNamePattern))
	}
	return current
}

// all getter func
func (cc *NamePattern) GetNamePatternServerHandler() string { return cc.NamePatternServerHandler }
func (cc *NamePattern) GetNamePatternRpcClient() string     { return cc.NamePatternRpcClient }
func (cc *NamePattern) GetNamePatternActorClient() string   { return cc.NamePatternActorClient }
func (cc *NamePattern) GetNamePatternActorServerHandlerMethod() string {
	return cc.NamePatternActorServerHandlerMethod
}
func (cc *NamePattern) GetNamePatternSingleConfPackage() string {
	return cc.NamePatternSingleConfPackage
}

// NamePatternVisitor visitor interface for NamePattern
type NamePatternVisitor interface {
	GetNamePatternServerHandler() string
	GetNamePatternRpcClient() string
	GetNamePatternActorClient() string
	GetNamePatternActorServerHandlerMethod() string
	GetNamePatternSingleConfPackage() string
}

// NamePatternInterface visitor + ApplyOption interface for NamePattern
type NamePatternInterface interface {
	NamePatternVisitor
	ApplyOption(...NamePatternOption) []NamePatternOption
}
