syntax = "proto3";
import "google/protobuf/descriptor.proto";

package protokit;
option go_package = "github.com/sandwich-go/protokit/option/gen/golang/protokit";

//CSHARP_NAMESPACE
extend google.protobuf.MessageOptions {
  OrmMessageOptions orm_message = 56801;
}

extend google.protobuf.FieldOptions {
  OrmFieldOptions orm_field = 56802;
}

extend google.protobuf.EnumOptions {
  OrmEnumOptions orm_enum = 56803;
}

extend google.protobuf.EnumValueOptions {
  EnumValueOptions enum_value = 56804;
}


message OrmEnumOptions {

}

message EnumValueOptions {

}

message OrmMessageOptions {
  // 是否生成数据库 message，对应原注释中的 Entry 标签
  bool model = 1;
  // 不走 dataserver 的缓存，对应原注释中的 NoCache 标签
  bool no_cache = 2;
  // 字符集，对应原注释中的 Charset 标签
  string charset = 3;
  // 表前缀，对应原注释中的 Prefix 标签
  string prefix = 4;
  // 是否生成属性同步 message，同时也会生成 数据库 message
  Bean bean = 5;
  // 是否是全局 hint，对应原注释中的 GlobalHint/Hint 标签
  Hint hint = 6;
  // 比较，对应原注释中的 Charset 标签
  string collate = 7;
  // 依赖锁
  string depend_lock = 8;
  // 锁
  Lock lock = 9;
  // 不记录日志
  bool no_log = 28;
  // 报警静默，例如字段长度超长，不会报警
  bool alert_silent = 29;
  // 是否是 gmt 类型的 message，对应 @schema
  GMTDynamic gmt_dynamic = 30;
  // 标记为 actor
  Actor actor = 10;
  // 依赖的 actor，比如公会成员，属于公会
  string depend_actor = 11;
}

message Actor {
  // actor 的名字，即 actor system name，必须定义
  string name = 1;
}

message GMTDynamic {

}

message OrmFieldOptions {
  // 是否是 Blob，对应原注释中的 Blob 标签
  Blob blob = 1;
  // 是否是 Text，对应原注释中的 Text 标签
  TextSize text = 2;
  // 唯一键，对应原注释中的 Unique 标签
  Unique unique = 3;
  // 索引，对应原注释中的 Index 标签
  Index index = 4;
  // 聚合索引，对应原注释中的 Aggregate 标签
  Index aggregate = 5;
  // 主键，对应原注释中的 Id 标签
  bool primary_key = 6;
  // hint，对应原注释中的 Hint 标签
  Hint hint = 7;
  // shard，cache 中分配的桶
  Hint shard = 8;
  // 标示某个属性是主键并且为自增，对应原注释中的 AutoIncrement 标签
  bool auto_increment = 9;
  // 大小，对应原注释中的 Size 标签
  int32 size = 10;
  // 默认值，对应原注释中的 Default 标签
  string default = 11;
  // int 类型，对应原注释中的 Int 标签
  Int int = 12;
  // decimal 类型，对应原注释中的 Decimal 标签
  Decimal decimal = 13;
  // 是否是 unsigned，对应原注释中的 Unsigned 标签
  bool unsigned = 14;
  // 注释，对应原注释中的 Comment 标签
  string comment = 15;
  // 压缩格式，对应原注释中的 Compress 标签
  Compress compress = 16;
  // sequence 序列，对应原注释中的 SIID 标签
  Sequence sequence = 17;
  // 是否是 search 属性，对应原注释中的 Search 标签
  bool search = 18;
  // read_only 是否只读
  bool read_only = 19;
  // 不同步给 client
  bool no_sync_client = 20;
  // 不同步给 db
  bool no_sync_db = 21;
  // 不同步
  bool no_sync = 22;
  // 依赖锁属性编号
  int32 depend_lock_num = 23;
  // 标记属性是否为版本属性，版本属性必须是 uint64 类型，例如 uint64、fixed64
  bool version = 24;
  // 意向锁的根部字段，之后的字段都是锁的字段
  bool intent_lock_root = 25;
  // 别名
  GoType go_type = 26;
  // bean 的 动态属性
  bool dynamic = 27;
  // 不记录日志
  optional bool no_log = 28;
  // 报警静默，例如字段长度超长，不会报警
  optional bool alert_silent = 29;
  // 为固定字符串类型
  bool char = 30;
  // 标记属性是否为生存时间属性，生存时间属性必须是 uint64 类型，例如 uint64、fixed64，单位为秒
  bool ttl = 31;
  // 分块起始number
  int32 chunking_begin_number = 32;
  // 分块结束number
  int32 chunking_end_number = 33;
  // 自定义的 golang tag
  map<string, string> tags = 34;
  // 标记不为空，即从数据库返回时，若没有数据，也不会空
  bool no_nil = 35;
  // 可见层级，默认使用protokitgo配置项max_view_level
  int32 view_level = 36;
  // 是否是gmt相关的属性
  GMT gmt = 37;
  // full text键，对应原注释中的 FullText 标签
  FullText full_text = 38;
  // 是否是 actor key 属性，如果定义，则表示该属性为 actor 的 id
  bool actor_key = 39;
  // 依赖 actor key 属性
  bool depend_actor_key = 40;
  bool phantom = 41;
  // 是否为字段生成mask方案
  bool mask = 42;
  // 是否为字段生成 encrypt/decrypt 方案
  string encrypt = 43;
}

message GMT {
  // 是否是 gmt_create 属性，支持 int64/uint64/string 类型
  bool is_create = 1;
  // 是否是 gmt_modified 属性，支持 int64/uint64/string 类型
  bool is_modified = 2;
}

// Bean bean 相关
message Bean {
  // 是否是一个 job
  bool job = 1;
}

// GoType 别名相关
message GoType {
  string package_alias = 1;
  string package_path = 2;
  string name = 3;
}

// Lock 锁相关
message Lock {
  // 锁的名称
  string name = 1;
  // 锁的优先级
  int32 priority = 2;
  // 是否需要生成意向锁
  bool intent = 3;
  // 是否是分布式锁
  bool distributed = 4;
}

// Sequence 序列相关
message Sequence {
  // 域
  string domain = 1;
  // 起始偏移量
  int64 offset_when_create_domain = 2;
}

// BlobSize blob 的大小
enum BlobSize {
  BLOB_SIZE_BLOB = 0;     // 默认的，blob，65K
  BLOB_SIZE_LONG = 1;     // long blob，4G
  BLOB_SIZE_MEDIUM = 2;   // medium blob，16M
  BLOB_SIZE_TINY = 3;     // tiny blob, 255b
}

// BlobCodec blob 序列化/反序列化方式
enum BlobCodec {
  BLOB_CODEC_OPT = 0;           // 优先使用 proto 方式进行 Marshal/Unmarshal，若数据非 proto.Message，则使用 msgpack 格式，推荐使用
  BLOB_CODEC_GOB = 1;           // Golang 原生 gob 方式进行 Marshal/Unmarshal
  BLOB_CODEC_MSG_PACK = 2;      // msgpack 格式进行 Marshal/Unmarshal
  BLOB_CODEC_NATIVE_JSON = 3;   // 使用原生 JSON 进行 Marshal/Unmarshal，序列化后的内容可视化，但如果数据中包含特殊的二进制数据，Marshal 后数据可能会丢失，不推荐使用
}

message Blob {
  BlobSize blob_size = 1;       // blob 的大小
  BlobCodec blob_codec = 2;     // blob 数据的序列化/反序列化方式
}

// TextSize text 的大小
enum TextSize {
  TEXT_SIZE_NONE = 0;           // 非 text
  TEXT_SIZE_TEXT = 1;           // text，65535个字符
  TEXT_SIZE_LONG = 2;           // long text，4G个字符
  TEXT_SIZE_MEDIUM = 3;         // medium text，16M个字符
  TEXT_SIZE_TINY = 4;           // tiny blob, 255个字符
}

// IntSize int 的大小
enum IntSize {
  INT_SIZE_INT = 0;             // int
  INT_SIZE_BIG = 1;             // big int
  INT_SIZE_MEDIUM = 2;          // medium int
  INT_SIZE_SMALL = 3;           // small int
  INT_SIZE_TINY = 4;            // tiny int
}

message Int {
  IntSize int_size = 1;       // int 的大小
}

// Decimal 数字
message Decimal {
  int32 precision = 1;          // The number of digits on both sides of the decimal point.
  int32 scale = 2;              // The number of digits to the right of the decimal point.
}

// Unique 唯一索引
message Unique {
  // 组集合
  repeated string groups = 1;
}

// Index 索引配置
message Index {
  // Generate the default index.
  bool default = 1;
  // Set the index groups.
  repeated IndexGroup groups = 2;
}

message FullText {
  // 组集合
  repeated string groups = 1;
}

message IndexGroup {
  // Set the index group.
  string group = 1;
  // Set the index group order.
  string order = 2;
}

// Hint 配置
message Hint {
  bool default = 1;             // 使用默认方式
  int32 manual = 2;             // 指定值
}

// Compress 压缩方式
enum Compress {
  COMPRESS_NONE = 0;            // 无压缩
  COMPRESS_GZIP = 1;            // gzip 压缩
  COMPRESS_SNAPPY = 2;          // snappy 压缩
}
