syntax = "proto3";
import "google/protobuf/descriptor.proto";

package protokit;
option go_package = "github.com/sandwich-go/protokit/option/gen/golang/protokit";

//CSHARP_NAMESPACE
extend google.protobuf.ServiceOptions {
  RpcServiceOptions rpc_service = 66801;
  BackOfficeServiceOptions back_office_service = 66802;
  bool job_service = 66803;
}

extend google.protobuf.MethodOptions {
  RpcMethodOptions rpc_method = 68801;
  BackOfficeMethodOptions back_office_method = 68802;
  JobMethodOptions job_method = 68803;
}

extend google.protobuf.MessageOptions {
  RpcMessageOptions rpc_message = 68804;
}

message JobMethodOptions {
    JobCreatorMethodOptions creator = 1;
}

message JobCreatorMethodOptions {
  int32 category = 1;
  bool  locker = 2;
}

message RpcServiceOptions {
  bool rpc = 1; // if (!rpc && !actor && !erpc) rpc = true
  bool actor = 2;
  bool erpc = 3;

  MethodAskType ask_tell = 11;
  string query_path = 12; // https://dcs-devcenter-site-online.auto.centurygame.io/docs-tools-protokitgo/v2.6/code/service/#querypath
  string lang_off = 13;
  QueryPathType query_path_snake_case = 14;
  bool actor_ask_reentrant = 15;
  bool grpc_style = 16; // 保持命名和grpc规则一致
  string actor_system_name = 17;//协议的actor system name，客户端在协议的meta中使用，默认为空不生成代码
  string labels = 18; // 自定义标签，描述该 Service 的类型与属性
}

enum MethodAskType {
  ASK = 0;
  TELL = 1;
  QUIT = 2;
}

enum QueryPathType {
  SNAKE_CASE = 0;
  CAMEL_CASE = 1;
}

enum CSProxyDefaultType {
  NONE = 0;
  ACTOR = 1;
  RPC = 2;
}

message BackOfficeServiceOptions {
  bool enable = 1;
  string name = 2;
  string comment = 3;
  bool only_for_simulator = 4;
}

message RpcMethodOptions {
  optional bool rpc = 1; // if (!rpc && !actor && !erpc) rpc = true
  optional bool actor = 2;
  optional bool erpc = 3;

  optional MethodAskType ask_tell = 11;
  string alias = 12;
  string actor_alias = 13;
  string lang_off = 14;
  optional bool actor_ask_reentrant = 15;
  bool quit = 16;
  optional bool grpc_style = 17; // 保持命名和grpc规则一致
  optional CSProxyDefaultType cs_proxy_default = 18; //cs客户端proxy代码默认方式 默认是None
  optional bool return_packet = 19; //go客户端调用函数额外返回整个packet 默认false
  optional bool async_call = 20; //客户端支持异步调用 只支持rpc 默认false
  optional string cs_actor_id_source = 21;//协议的meta的actor id的来源，这个值对应request协议里面的字段名，字段支持数字和string类型。默认为空协议使用用户id
  optional string labels = 22; // 自定义标签，描述该RPC的类型与属性
}

message BackOfficeMethodOptions {
  bool enable = 1;
  string name = 2;
  string comment = 3;
  bool only_for_simulator = 4;
}

message RpcMessageOptions {
  bool notify = 1; //是否是notify
}